name: Continuous Deployment

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 1

      - name: Login to Docker Registry
        uses: docker/login-action@v1
        with:
          registry: registry.moveyourdigital.dev
          username: ${{ secrets.DOCKER_REGISTRY_USERNAME }}
          password: ${{ secrets.DOCKER_REGISTRY_PASSWORD }}

      - name: Build and Push to Docker Registry
        uses: docker/build-push-action@v2
        with:
          context: .
          platforms: linux/amd64
          push: true
          tags: registry.moveyourdigital.dev/github/actions-runner:latest

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
