name: Continuous Deployment

on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  deployment:
    runs-on: [self-hosted, linux]
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Login to Docker Registry
        uses: docker/login-action@v2
        with:
          registry: registry.moveyourdigital.dev
          username: ${{ secrets.DOCKER_REGISTRY_USERNAME }}
          password: ${{ secrets.DOCKER_REGISTRY_PASSWORD }}

      - name: Build and Push to Docker Registry
        uses: docker/build-push-action@v2
        with:
          context: .
          platforms: linux/amd64
          push: true
          network: host
          tags: registry.moveyourdigital.dev/github/actions-runner:latest
          cache-from: type=registry,ref=github/actions-runner:latest
          cache-to: type=inline

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
